services:
  docker-backend-2:
    image: reitansora/docker-backend-2
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - docker-network

networks:
  docker-network:
    external: true