services:
  docker-backend-1:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - docker-network

networks:
  docker-network:
    external: true
