services:
  docker-frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - dockertest_docker-network

networks:
  dockertest_docker-network:
    external: true