services:
  docker-frontend:
    image: reitansora/docker-frontend:latest
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - docker-network

networks:
  docker-network:
    external: true